apiVersion: apps/v1
kind: Deployment
metadata:
  name: justinliu2010-app
  labels:
    app: justinliu2010-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: justinliu2010-app
  template:
    metadata:
      labels:
        app: justinliu2010-app
    spec:
      containers:
        - name: justinliu2010-app
          image: asia-east1-docker.pkg.dev/smiling-stock-425106-c9/devops-repo/justinliu2010-app:latest
          ports:
            - containerPort: 80
